### ISSUE TITLE
[Bug] - testdb.test.ts fails occasionally

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Hangar#86]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find an existing bug.

## Description

`testdb.test.ts` sporadically fails

## Expected Behavior

`testdb.test.ts` should always pass

## Actual Behavior

`testdb.test.ts` occasionally fails and requires that the tests be re-run.

## Steps to Reproduce

Unknown

## Other Information

[Example failure](https://github.com/AmericanAirlines/Hangar/runs/405624992), however, error shown in output (included below) is likely unrelated and just happened to print at the same time as the actual error. The issue likely stems from opening/closing several DBs while the test files are run in parallel. We may need to migrate the test DB to a singleton and simply drop data instead of closing the DB/dropping tables.
``` 
An API error occurred: invalid_auth
      at Object.platformErrorFromResult (node_modules/@slack/web-api/src/errors.ts:94:5)
      at WebClient.apiCall (node_modules/@slack/web-api/src/WebClient.ts:159:13)
```

**Comment by SpencerKaiser** [comment]
Closing; this was likely a result of the issue with the Slack SDK
